// SPDX-FileCopyrightText: 2026 AgentKitten Authors
// SPDX-License-Identifier: Apache-2.0
//
// This file is auto-generated by Scripts/generate-version.sh.

/// Core building blocks for AgentKitten.
public enum AgentKittenCore {
    /// Library version identifier.
    public static let version = "0.0.5"
}
