// SPDX-FileCopyrightText: 2026 AgentKitten Authors
// SPDX-License-Identifier: Apache-2.0

import Foundation

/// Generic opaque identifier wrapper with a compile-time tag.
public struct TypedID<Tag>: Sendable, Hashable, Codable, CustomStringConvertible {
    private let rawValue: String

    init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static func generate() -> Self {
        Self(rawValue: UUID().uuidString)
    }

    /// A human-readable representation equal to the raw backing string.
    public var description: String {
        rawValue
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        rawValue = try container.decode(String.self)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public enum AgentIDTag {}
public enum AgentSessionIDTag {}
public enum InvocationIDTag {}
public enum EventIDTag {}
enum ConversationIDTag {}
enum InferenceSessionIDTag {}

// MARK: - UserID

/// A stable identifier for a user of the agent system.
///
/// For single-user apps, use ``local``. For multi-user or authenticated
/// scenarios, supply the external identity string (e.g. an Auth0 `sub`).
///
/// The backing representation is an implementation detail — construct
/// via ``init(_:)``; never assume the raw format.
public struct UserID: Sendable, Hashable, Codable, CustomStringConvertible, ExpressibleByStringLiteral {
    private let rawValue: String

    /// Creates a user identifier from the given string.
    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init(stringLiteral value: String) {
        self.init(value)
    }

    /// The default local user, used in single-user apps.
    ///
    /// Stable across sessions: always resolves to the fixed identifier `"_local"`.
    public static let local = UserID("_local")

    /// A human-readable representation equal to the raw backing string.
    public var description: String {
        rawValue
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        rawValue = try container.decode(String.self)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

// MARK: - AgentID

/// A stable identifier for an agent definition.
///
/// Use a short, human-readable name such as `"weatherAgent"`.
/// Path or segment structure is deferred to a future version; a flat
/// string is sufficient for V1.
///
/// The backing representation is an implementation detail — construct
/// via ``init(_:)``.
public typealias AgentID = TypedID<AgentIDTag>

extension AgentID {
    /// Creates an agent identifier from the given string.
    public init(_ rawValue: String) {
        self.init(rawValue: rawValue)
    }

    /// Creates a new, unique agent identifier backed by a UUID.
    ///
    /// Use this when you don't need a stable, human-readable name.
    public static func generate() -> Self {
        Self(rawValue: UUID().uuidString)
    }
}

extension AgentID: ExpressibleByUnicodeScalarLiteral,
    ExpressibleByExtendedGraphemeClusterLiteral,
    ExpressibleByStringLiteral {
    public init(unicodeScalarLiteral value: String) {
        self.init(value)
    }

    public init(extendedGraphemeClusterLiteral value: String) {
        self.init(value)
    }

    public init(stringLiteral value: String) {
        self.init(value)
    }
}

// MARK: - AgentSessionID

/// An opaque identifier for a single agent session.
///
/// Agent session identifiers are always generated by the library — use
/// ``generate()`` to obtain a new identifier.
public typealias AgentSessionID = TypedID<AgentSessionIDTag>

// MARK: - InvocationID

/// An opaque identifier for a single agent invocation.
///
/// Groups all events produced by one `AgentSession.send()` turn,
/// enabling trace reconstruction. Always generated by the library —
/// use ``generate()`` to obtain a new identifier.
public typealias InvocationID = TypedID<InvocationIDTag>

// MARK: - EventID

/// An opaque identifier for a single emitted agent event.
///
/// Event identifiers are always generated by the library and are used for
/// trace reconstruction via ``AgentEvent/Metadata/eventID`` and
/// ``AgentEvent/Metadata/parentEventID``.
public typealias EventID = TypedID<EventIDTag>

// MARK: - Internal runtime IDs

typealias ConversationID = TypedID<ConversationIDTag>

typealias InferenceSessionID = TypedID<InferenceSessionIDTag>

struct ConversationIdentity: Sendable, Hashable, Codable {
    let conversationID: ConversationID
    let inferenceSessionID: InferenceSessionID
}
