#!/bin/bash

# Adapted from:
# https://github.com/elevenlabs/elevenlabs-swift-sdk/blob/main/Scripts/generate-version.sh
#
# Generates Sources/AgentKittenCore/AgentKittenCore.swift from the latest git tag.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION_FILE="$ROOT_DIR/Sources/AgentKittenCore/AgentKittenCore.swift"

# Get the latest git tag, defaulting to "0.0.0" if no tags exist.
VERSION="$(git -C "$ROOT_DIR" describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")"

# Remove a leading "v" prefix if present.
VERSION="${VERSION#v}"

cat > "$VERSION_FILE" <<EOF
// SPDX-FileCopyrightText: 2026 AgentKitten Authors
// SPDX-License-Identifier: Apache-2.0
//
// This file is auto-generated by Scripts/generate-version.sh.

/// Core building blocks for AgentKitten.
public enum AgentKittenCore {
    /// Library version identifier.
    public static let version = "$VERSION"
}
EOF

echo "Generated AgentKittenCore.swift with version: $VERSION"
